// <auto-generated />
using System;
using DiarioTreino.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiarioTreino.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(DiarioTreinoDbContext))]
    partial class DiarioTreinoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiarioTreino.Domain.Catalogo.Exercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_id");

                    b.Property<string>("GrupoMuscular")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("grupo_muscular");

                    b.Property<short>("IntensidadeMetricaPadraoId")
                        .HasColumnType("smallint")
                        .HasColumnName("intensidade_metrica_padrao_id");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modalidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<short>("VolumeMetricaPadraoId")
                        .HasColumnType("smallint")
                        .HasColumnName("volume_metrica_padrao_id");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("IntensidadeMetricaPadraoId");

                    b.HasIndex("VolumeMetricaPadraoId");

                    b.ToTable("exercicio", null, t =>
                        {
                            t.HasCheckConstraint("ck_exercicio_modalidade", "modalidade IN ('FORCA','ISOMETRIA','CARDIO')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Ativo = true,
                            GrupoMuscular = "peito",
                            IntensidadeMetricaPadraoId = (short)1,
                            Modalidade = "FORCA",
                            Nome = "Supino reto",
                            VolumeMetricaPadraoId = (short)10
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Ativo = true,
                            GrupoMuscular = "peito",
                            IntensidadeMetricaPadraoId = (short)1,
                            Modalidade = "FORCA",
                            Nome = "Supino inclinado",
                            VolumeMetricaPadraoId = (short)10
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Ativo = true,
                            GrupoMuscular = "peito",
                            IntensidadeMetricaPadraoId = (short)1,
                            Modalidade = "FORCA",
                            Nome = "Crucifixo",
                            VolumeMetricaPadraoId = (short)10
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            Ativo = true,
                            GrupoMuscular = "tríceps",
                            IntensidadeMetricaPadraoId = (short)1,
                            Modalidade = "FORCA",
                            Nome = "Tríceps corda",
                            VolumeMetricaPadraoId = (short)10
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            Ativo = true,
                            GrupoMuscular = "pernas",
                            IntensidadeMetricaPadraoId = (short)1,
                            Modalidade = "FORCA",
                            Nome = "Agachamento livre",
                            VolumeMetricaPadraoId = (short)10
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            Ativo = true,
                            GrupoMuscular = "costas",
                            IntensidadeMetricaPadraoId = (short)1,
                            Modalidade = "FORCA",
                            Nome = "Remada curvada",
                            VolumeMetricaPadraoId = (short)10
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            Ativo = true,
                            GrupoMuscular = "core",
                            IntensidadeMetricaPadraoId = (short)2,
                            Modalidade = "ISOMETRIA",
                            Nome = "Prancha",
                            VolumeMetricaPadraoId = (short)11
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            Ativo = true,
                            GrupoMuscular = "pernas",
                            IntensidadeMetricaPadraoId = (short)2,
                            Modalidade = "ISOMETRIA",
                            Nome = "Agachamento isométrico",
                            VolumeMetricaPadraoId = (short)11
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            Ativo = true,
                            IntensidadeMetricaPadraoId = (short)3,
                            Modalidade = "CARDIO",
                            Nome = "Corrida",
                            VolumeMetricaPadraoId = (short)11
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            Ativo = true,
                            IntensidadeMetricaPadraoId = (short)3,
                            Modalidade = "CARDIO",
                            Nome = "Bicicleta",
                            VolumeMetricaPadraoId = (short)11
                        });
                });

            modelBuilder.Entity("DiarioTreino.Domain.Catalogo.Metrica", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Eixo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("eixo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("metrica", null, t =>
                        {
                            t.HasCheckConstraint("ck_metrica_eixo", "eixo IN ('INTENSIDADE','VOLUME')");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Codigo = "CARGA_KG",
                            Eixo = "INTENSIDADE",
                            Nome = "Carga",
                            Unidade = "kg"
                        },
                        new
                        {
                            Id = (short)2,
                            Codigo = "PESO_CORPORAL",
                            Eixo = "INTENSIDADE",
                            Nome = "Peso corporal",
                            Unidade = "-"
                        },
                        new
                        {
                            Id = (short)3,
                            Codigo = "ZONA",
                            Eixo = "INTENSIDADE",
                            Nome = "Zona",
                            Unidade = "1 a 5"
                        },
                        new
                        {
                            Id = (short)10,
                            Codigo = "REPETICOES",
                            Eixo = "VOLUME",
                            Nome = "Repetições",
                            Unidade = "rep"
                        },
                        new
                        {
                            Id = (short)11,
                            Codigo = "TEMPO_SEG",
                            Eixo = "VOLUME",
                            Nome = "Tempo",
                            Unidade = "s"
                        },
                        new
                        {
                            Id = (short)12,
                            Codigo = "DISTANCIA_M",
                            Eixo = "VOLUME",
                            Nome = "Distância",
                            Unidade = "m"
                        });
                });

            modelBuilder.Entity("DiarioTreino.Domain.Execucao.SerieExecutada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short?>("DescansoSeg")
                        .HasColumnType("smallint")
                        .HasColumnName("descanso_seg");

                    b.Property<Guid>("ExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercicio_id");

                    b.Property<decimal?>("Intensidade")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("intensidade");

                    b.Property<short>("IntensidadeMetricaId")
                        .HasColumnType("smallint")
                        .HasColumnName("intensidade_metrica_id");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem");

                    b.Property<short>("Rodada")
                        .HasColumnType("smallint")
                        .HasColumnName("rodada");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("TreinoExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_exercicio_id");

                    b.Property<decimal>("Volume")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("volume");

                    b.Property<short>("VolumeMetricaId")
                        .HasColumnType("smallint")
                        .HasColumnName("volume_metrica_id");

                    b.HasKey("Id");

                    b.HasIndex("IntensidadeMetricaId");

                    b.HasIndex("SessaoId")
                        .HasDatabaseName("ix_serie_executada_sessao");

                    b.HasIndex("TreinoExercicioId");

                    b.HasIndex("VolumeMetricaId");

                    b.HasIndex("ExercicioId", "SessaoId")
                        .HasDatabaseName("ix_serie_executada_exercicio_sessao");

                    b.ToTable("serie_executada", null, t =>
                        {
                            t.HasCheckConstraint("ck_serie_executada_tipo", "tipo IN ('ESFORCO','RECUPERACAO')");

                            t.HasCheckConstraint("ck_serie_executada_volume", "volume >= 0");
                        });
                });

            modelBuilder.Entity("DiarioTreino.Domain.Execucao.Sessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta_id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<short?>("DuracaoMin")
                        .HasColumnType("smallint")
                        .HasColumnName("duracao_min");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("RegistradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_id");

                    b.Property<Guid?>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("TreinoId");

                    b.HasIndex("AtletaId", "Data")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sessao_atleta_data");

                    b.ToTable("sessao", null, t =>
                        {
                            t.HasCheckConstraint("ck_sessao_data", "data <= current_date + 1");
                        });
                });

            modelBuilder.Entity("DiarioTreino.Domain.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("DiarioTreino.Domain.Identidade.UsuarioPapel", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Papel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("papel");

                    b.HasKey("UsuarioId", "Papel");

                    b.ToTable("usuario_papel", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuario_papel_papel", "papel IN ('ATLETA','EDUCADOR')");
                        });
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.EtapaPrescrita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("IntensidadeAlvo")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("intensidade_alvo");

                    b.Property<short>("IntensidadeMetricaId")
                        .HasColumnType("smallint")
                        .HasColumnName("intensidade_metrica_id");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("TreinoExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_exercicio_id");

                    b.Property<decimal?>("VolumeAlvo")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("volume_alvo");

                    b.Property<short>("VolumeMetricaId")
                        .HasColumnType("smallint")
                        .HasColumnName("volume_metrica_id");

                    b.HasKey("Id");

                    b.HasIndex("IntensidadeMetricaId");

                    b.HasIndex("TreinoExercicioId");

                    b.HasIndex("VolumeMetricaId");

                    b.ToTable("etapa_prescrita", null, t =>
                        {
                            t.HasCheckConstraint("ck_etapa_prescrita_tipo", "tipo IN ('ESFORCO','RECUPERACAO')");
                        });
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.PlanoTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid")
                        .HasColumnName("atleta_id");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<DateOnly?>("Fim")
                        .HasColumnType("date")
                        .HasColumnName("fim");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("date")
                        .HasColumnName("inicio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId")
                        .IsUnique()
                        .HasDatabaseName("ux_plano_atleta_ativo")
                        .HasFilter("ativo");

                    b.HasIndex("AutorId");

                    b.ToTable("plano_treino", (string)null);
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.Treino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nome");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId", "Ordem")
                        .HasDatabaseName("ix_treino_plano_ordem");

                    b.ToTable("treino", (string)null);
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.TreinoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short?>("DescansoAlvoSeg")
                        .HasColumnType("smallint")
                        .HasColumnName("descanso_alvo_seg");

                    b.Property<Guid>("ExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercicio_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observacao");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem");

                    b.Property<short>("Rodadas")
                        .HasColumnType("smallint")
                        .HasColumnName("rodadas");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("TreinoId", "Ordem")
                        .HasDatabaseName("ix_treino_exercicio_treino_ordem");

                    b.ToTable("treino_exercicio", null, t =>
                        {
                            t.HasCheckConstraint("ck_treino_exercicio_rodadas", "rodadas > 0");
                        });
                });

            modelBuilder.Entity("DiarioTreino.Domain.Vinculos.Vinculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<Guid>("EducadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("educador_id");

                    b.Property<DateTimeOffset?>("Fim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim");

                    b.Property<DateTimeOffset?>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_vinculo_aluno_ativo")
                        .HasFilter("status = 'ATIVO'");

                    b.HasIndex("EducadorId", "AlunoId")
                        .IsUnique()
                        .HasDatabaseName("ux_vinculo_aberto")
                        .HasFilter("status IN ('PENDENTE','ATIVO')");

                    b.ToTable("vinculo", null, t =>
                        {
                            t.HasCheckConstraint("ck_vinculo_educador_diferente_aluno", "educador_id <> aluno_id");

                            t.HasCheckConstraint("ck_vinculo_status", "status IN ('PENDENTE','ATIVO','ENCERRADO')");
                        });
                });

            modelBuilder.Entity("DiarioTreino.Domain.Catalogo.Exercicio", b =>
                {
                    b.HasOne("DiarioTreino.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiarioTreino.Domain.Catalogo.Metrica", "IntensidadeMetricaPadrao")
                        .WithMany()
                        .HasForeignKey("IntensidadeMetricaPadraoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Catalogo.Metrica", "VolumeMetricaPadrao")
                        .WithMany()
                        .HasForeignKey("VolumeMetricaPadraoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IntensidadeMetricaPadrao");

                    b.Navigation("VolumeMetricaPadrao");
                });

            modelBuilder.Entity("DiarioTreino.Domain.Execucao.SerieExecutada", b =>
                {
                    b.HasOne("DiarioTreino.Domain.Catalogo.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Catalogo.Metrica", null)
                        .WithMany()
                        .HasForeignKey("IntensidadeMetricaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Execucao.Sessao", "Sessao")
                        .WithMany("Series")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Planejamento.TreinoExercicio", "TreinoExercicio")
                        .WithMany()
                        .HasForeignKey("TreinoExercicioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiarioTreino.Domain.Catalogo.Metrica", null)
                        .WithMany()
                        .HasForeignKey("VolumeMetricaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Sessao");

                    b.Navigation("TreinoExercicio");
                });

            modelBuilder.Entity("DiarioTreino.Domain.Execucao.Sessao", b =>
                {
                    b.HasOne("DiarioTreino.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Planejamento.Treino", null)
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DiarioTreino.Domain.Identidade.UsuarioPapel", b =>
                {
                    b.HasOne("DiarioTreino.Domain.Identidade.Usuario", "Usuario")
                        .WithMany("Papeis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.EtapaPrescrita", b =>
                {
                    b.HasOne("DiarioTreino.Domain.Catalogo.Metrica", "IntensidadeMetrica")
                        .WithMany()
                        .HasForeignKey("IntensidadeMetricaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Planejamento.TreinoExercicio", "TreinoExercicio")
                        .WithMany("Etapas")
                        .HasForeignKey("TreinoExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Catalogo.Metrica", "VolumeMetrica")
                        .WithMany()
                        .HasForeignKey("VolumeMetricaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IntensidadeMetrica");

                    b.Navigation("TreinoExercicio");

                    b.Navigation("VolumeMetrica");
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.PlanoTreino", b =>
                {
                    b.HasOne("DiarioTreino.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.Treino", b =>
                {
                    b.HasOne("DiarioTreino.Domain.Planejamento.PlanoTreino", "Plano")
                        .WithMany("Treinos")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.TreinoExercicio", b =>
                {
                    b.HasOne("DiarioTreino.Domain.Catalogo.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Planejamento.Treino", "Treino")
                        .WithMany("Exercicios")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("DiarioTreino.Domain.Vinculos.Vinculo", b =>
                {
                    b.HasOne("DiarioTreino.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioTreino.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EducadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiarioTreino.Domain.Execucao.Sessao", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("DiarioTreino.Domain.Identidade.Usuario", b =>
                {
                    b.Navigation("Papeis");
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.PlanoTreino", b =>
                {
                    b.Navigation("Treinos");
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.Treino", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("DiarioTreino.Domain.Planejamento.TreinoExercicio", b =>
                {
                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
